on: [push, pull_request]

name: Continuous integration

jobs:
  style_lint:
    name: Coding style & Linting
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install rustfmt & clippy
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  check_tests:
      name: Check code & Run tests
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2

        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            override: true

        - name: Check
          uses: actions-rs/cargo@v1
          with:
            command: check

        - name: Tests
          uses: actions-rs/cargo@v1
          with:
            command: test

  binary_build:
    if: |
      github.event == 'push' &&
      github.ref == 'refs/heads/master'
    name: Binary build in release mode
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build --release
